### ISSUE TITLE
Vendor name

### ISSUE THREAD

**Issue by koriym** [kawanamiyuu/Kawanamiyuu.VuejsSpa#2]
相談です！

マニュアルも整備してBEARのorgレポジトリに移すのはどうでしょうか？

TwigModuleのように個人リポジトリでホストしてもOKですが、その時はベンダー名を個人の`Kawanamiyuu`にするのが良いのではないでしょうか？どうでしょう？？🤔

参考：
`Madapaja.TwigModule`
https://github.com/madapaja/Madapaja.TwigModule

**Comment by kawanamiyuu** [comment]
もうすこし実験的にVue.jsとBEAR.Sundayの組み合わせを試したいので、いったんベンダー名を`Kawanamiyuu`とする方向で対応します！ :pray:

> マニュアルも整備してBEARのorgレポジトリに移す

その際はまた相談させてください！

**Comment by koriym** [comment]
いいと思います！😌
